### ISSUE TITLE
Suppression List - Search query param Sources

### ISSUE THREAD

**Issue by bdeanindy** [SparkPost/sparkpost-api-documentation#1]
There are 3 issues with the Suppression List Search for Entries currently:
1. Source[s] is not a documented property in the Headers of the Live Console (see URL below), but is required.
2. In the Human Readable documentation, the property is called "source", but in the error message from Debugging Proxy and Production says it is called "sources"...is it singular or plural?
3. Human Readable documentation says that "source" is NOT a required property, but the API response says it is...which one is right?

Please use the live console to search a Suppression List here:
https://www.sparkpost.com/api#/reference/suppression-list/bulk-insertupdate/search-for-suppression-list-entries?console=1

You'll get an error the following error message using the Debugging Proxy or Production:

```
{
  "errors": [
    {
      "param": "sources",
      "message": "sources must be in list: Bounce Rule, Compliance, List Unsubscribe, Manually Added, Spam Complaint, Unsubscribe Link",
      "value": "sources"
    }
  ]
}   
```

**Comment by bdeanindy** [comment]
@bizob2828 could you take a look at this issue and provide some clarification so we can improve documentation to match the API spec please?

**Comment by ewandennis** [comment]
Oldest issue evar. Singular `source` for suppression list entries returned by search, plural `sources` in query parameters when searching for entries from particular sources.
