### ISSUE TITLE
Suppression List - "Delete a List Entry" example fails

### ISSUE THREAD

**Issue by aydrian** [SparkPost/sparkpost-api-documentation#13]
Example using Mock Server returns "API call failed"

**Comment by richleland** [comment]
Looks like this might be a bug in Apiary. I've reached out to their support team.

**Comment by richleland** [comment]
Received the following from Apiary:

> Hi Richard,
>  this is bug at our side. Please add header to `Content-Length: 0` to your `Response 204` as in example: https://jsapi.apiary.io/apis/deleteendpoint.apib and this will work. 
> Let me know if I can help with anything else.
> Regards,
> Ladislav

However, after trying this and still getting no result, I'm not convinced this is the only issue with our docs. Especially since we have #10, #11, and #12.

**Comment by colestrode** [comment]
we're no longer on apiary, closing
