### ISSUE TITLE
Fix validation warnings

### ISSUE THREAD

**Issue by orval** [SparkPost/sparkpost-api-documentation#18]
Running `api-blueprint-validator apiary.apib` produces 76 warnings currently.

They are being ignored at the moment, and that might not be an issue. But it would be nice to get them fixed in case it can improve the experience.

I used https://github.com/danielgtaylor/aglio to render the docs into HTML and fixing up the first warning I found did fix a small bit of broken rendering.

**Comment by ewandennis** [comment]
We're moving away from that pipeline to avoid this type of issue :)
