### ISSUE TITLE
Will the Sparkpost API implement full versioning for mapping?

### ISSUE THREAD

**Issue by bdeanindy** [SparkPost/sparkpost-api-documentation#2]
Currently the Sparkpost API Endpoint is: https://api.sparkpost.com/api/v1

Are there plans to implement full semantic versioning (following semver.org either v1.0.x or v2.0.x) for the Sparkpost API providing consuming developers and SDK builders the ability to map to fixed (major, minor, and patch) versions of the API?

Example: https://api.sparkpost.com/api/v1.0.0 as the endpoint

Since we've opened our API Documentation, we should probably begin following semantic version best practices and wanted to find out our official standpoint.

**Comment by richleland** [comment]
We will address this within engineering when if/when we get to a point where we need to bump the API version.
