### ISSUE TITLE
Sandbox sending domain - no explanation

### ISSUE THREAD

**Issue by vercotux** [SparkPost/sparkpost-api-documentation#22]
What is a "sandbox sending domain"? Mentioned only briefly in the API docs under the "[sandbox](https://developers.sparkpost.com/api/#/reference/transmissions)" option. How does one "use" it? Where is it configured/added? There is no further mention of this topic in any SparkPost documentation, nor is there any such item/setting/menu in the SparkPost dashboard.

**Comment by npahucki** [comment]
I want to know the same, please answer this!

**Comment by mrthan** [comment]
I'm searching to no avail as well. There's the relatively new "sinkhole" option with [details in support](https://support.sparkpost.com/customer/en/portal/articles/2361300-how-to-test-integrations
). But, this doesn't mention sandbox or whether sandbox might offer a preview (fingers crossed)

Actually, I think it's something introduced with the new Heroku addon. A limited 50 send option from @sparkpostbox.com
https://support.sparkpost.com/customer/en/portal/articles/2207582-using-the-sparkpost-heroku-add-on

**Comment by ewandennis** [comment]
Good feedback, thanks.  [Docs now updated with a description of the sandbox domain facility](https://developers.sparkpost.com/api/transmissions#header-the-sandbox-domain).
