### ISSUE TITLE
Most of the python example code is missing the header object

### ISSUE THREAD

**Issue by tyrocca** [SparkPost/sparkpost-api-documentation#24]
For example:
This is the code the console gives for [retrieving a transmission](https://developers.sparkpost.com/api/#/reference/transmissions/create/retrieve-a-transmission?console=1)
```
from urllib2 import Request, urlopen
request = Request('https://api.sparkpost.com/api/v1/transmissions/123456789')
response_body = urlopen(request).read()
print response_body
```

It should be 
```
from urllib2 import Request, urlopen
headers = {
  'Accept': 'application/json',
  'Authorization': '<some_api_key>'
}
request = Request('https://api.sparkpost.com/api/v1/transmissions/12345656789', headers=headers)
response_body = urlopen(request).read()
print response_body
```
This is a problem on almost all python requests

**Comment by richleland** [comment]
We no longer use Apiary and have removed code samples in favor of using the [python-sparkpost](https://github.com/SparkPost/python-sparkpost) client library.
