### ISSUE TITLE
Webhooks - Events Documentation and Samples Failing

### ISSUE THREAD

**Issue by bdeanindy** [SparkPost/sparkpost-api-documentation#3]
It appears that the endpoint for these two actions on the Webhooks resource are not picking up the correct endpoint.

Here is the URL that is being used in the request instead of https://api.sparkpost.com (while having the Production server selected in the console):
https://private-ab6bb-sparkpostapi.apiary-proxy.com/api/v1/webhooks/events

**Comment by bdeanindy** [comment]
OK. After testing several times in a couple of different browsers. There is a problem with the Webhooks documentation for Events/Samples which causes all of our other API documentation to fail (after a single usage). All requests are later sent to the Debugging Proxy, which doesn't seem to be operating once used with the above resource actions.

**Comment by colestrode** [comment]
out of date, closing
