### ISSUE TITLE
API call to message-events, document default "from" and/or align it with 10 days retention policy

### ISSUE THREAD

**Issue by gmartinez** [SparkPost/sparkpost-api-documentation#32]
---------- Forwarded message ----------
From: <support@sparkpost.com>
Date: Thu, Jan 19, 2017 at 6:20 PM
Subject: Re: API call not working...
To: gonzalo@npressive.com

SparkPost Support wrote:
Hi,

Also you can go to to this page https://github.com/SparkPost/sparkpost-api-documentation
and submit an" Issue" or “Pull Requests”

Regards,
Support Team

How satisfied were you with the support we provided today?
 Great |  Good |  Fair |  Poor
SparkPost Support wrote:
Hi,

Thanks for your email. Yes you are right we don’t have a default value for “From” in the API. 
I will let our product team know to add that to our API documentation. Thanks for your feedback.

Regards,
Support Team

JAN 19, 2017  |  11:29AM PST 
Gonzalo wrote:
Mmm...interesting, I was actually not specifying a "from", since it does
not show as required in the documentation plus since I am asking directly
for a specific message id I tend to think that should not be necessary.

(yes, adding a "from" with a sensible value do the trick)

So, there seems to be a default "from" that applies if not stated, right ?
what is it ? is it documented ?

In any case it really strikes me as odd how it is implemented though,
wouldn't it make more sense that it was aligned with the 10 days retention
policy for message-events ?

Anyway, I appreciate your response I will see to adapt my code so I always
have a from that is "$now - 10 days" :)
SparkPost Support wrote:
Hi,

Thanks for your email. I see injection and delivery for that message ID on January 17th. Are you sure you use the correct time frame in the call ?

Regards,
Support Team

JAN 19, 2017  |  06:53PM PST 
Original message
Gonzalo wrote:

Call to endpoint "message-events" not working today (it was a couple of days ago);

https://api.sparkpost.com/api/v1/message-events?message_ids=0004ca397e58521f999c

My Headers;

Content-Type: application/json
Authorization: ************************************************

Response is;

{
"results": [],
"total_count": 0,
"links": [],
}

**Comment by ewandennis** [comment]
Resolved.
