### ISSUE TITLE
Scheduled sending not available via smtp API

### ISSUE THREAD

**Issue by tuck1s** [SparkPost/sparkpost-api-documentation#33]
smtp-api.md includes its own list of options, which differ in some detail from the main transmission API options.
It may be helpful to point out the scheduled sending - via options.start_time - is NOT available via SMTP currently.

**Comment by ewandennis** [comment]
The list of SMTP API options doesn't not list `start_time`, which I hope makes this point. Describing the delta of SMTP vs. API options will quickly get onerous. Will revisit as and when we get community feedback on this.
