### ISSUE TITLE
Remove "Delete by Campaign ID" from the API Docs

### ISSUE THREAD

**Issue by ikim28** [SparkPost/sparkpost-api-documentation#35]
The following section for discussion: https://developers.sparkpost.com/api/transmissions.html#transmissions- delete-transmissions-by-campaign-delete

This functionality does not work for all SPE and SPC customers, it's limited to only 2 SPE customers. I've tested in SP.com on a free account, and although you get the "204 no content" upon attempting to delete, the campaigns definitely were not cancelled.

As this only applies to two SPE customers, I do not think it should be public facing to all customers within the API docs.

**Comment by ewandennis** [comment]
Feature marked as "Enterprise only - specific customer configuration"
