### ISSUE TITLE
Inlining CSS - Explain where the style should initially go in the template/html

### ISSUE THREAD

**Issue by begedin** [SparkPost/sparkpost-api-documentation#37]
I've encountered this issue while trying to get CSS to inline in our own project. I created a template and put the `<style>`block into the `<body>`. Even though the `inline_css` option was correctly set, the css was not inlining in my emails. 

The solution was to put the `<style>` block into the `<head>`. This is probably common knowledge, but it escaped me, so I would not be surprised if it escaped others to. Mentioning this somewhere would be useful.

Also something that could be a bit clearer. In the case of inlining css for templates, an explicit statement of what is considered the correct approach would be useful. Should we:

A. Create the template with the option `inline_css: true`
B. Send the transmission with the option `inline_css: true`
C. Both
D. Something else entirely

**Comment by yargevad** [comment]
Hi @begedin - you're right, that could be made more clear, thanks!

**Comment by yargevad** [comment]
I added a note to the `inline_css` option in the SMTP and Transmission sections.

Templates and Transmissions do share some options, however `inline_css` isn't one of them. That should always be specified with the Transmission if CSS should be inlined.

Thanks again for the feedback!
