### ISSUE TITLE
Tracking Domains endpoint docs need to be updated to say https is supported

### ISSUE THREAD

**Issue by cristoirmac** [SparkPost/sparkpost-api-documentation#41]
We now support https https://www.sparkpost.com/docs/tech-resources/enabling-https-engagement-tracking-on-sparkpost/

This section is no longer relevant.  Perhaps replace with a link to the doc?
"Note: For SparkPost, only HTTP is supported on tracking domains since SparkPost does not issue SSL certificates for customer domains. As a result, port should be set to 80 and secure to false when creating your tracking domain."

**Comment by rajumsys** [comment]
https://github.com/SparkPost/sparkpost-api-documentation-DEV/pull/297
