### ISSUE TITLE
The example template id returned in the POST isn't correct

### ISSUE THREAD

**Issue by cristoirmac** [SparkPost/sparkpost-api-documentation#47]
The response in the example should be "summer_sale" not "11806290401558530".  

 POST /api/v1/templates

{
  "name": "Summer Sale!",
  "shared_with_subaccounts": false,
  "content": {
    "from": "marketing@bounces.company.example",
    "subject": "Summer deals",
    "html": "<b>Check out these deals!</b>"
  }
}

Response (HTTP status code: 200)

{
  "results": {
    "id": "11806290401558530"
  }
}

**Comment by rdawemsys** [comment]
@cristoirmac I think you might be getting the examples mixed up? That particular JSON doesn't specify a value for the "id" field in the POST data. So, the Templates API will assign an auto-generated unique ID to that template, and return it in the response.

There are other examples later in the Templates API where the "id" field is specified in the POST, and the ID in the response is the one specified in the request.

The docs say:

> The following are key points about creating parts in your templates, as shown in the example:
> 
>     The id field may be supplied, and it must be unique.

I checked the responses and they all look fine to me. The ones where "id" is specified in the request have the same ID in the response. The ones where there is no "id" in the request have an auto-generated ID in the response.

**Comment by avigoldman** [comment]
I also went through and created a template with the sample JSON and, like Rich said, if the `id` field isn't specified, the API generates a random ID.
