### ISSUE TITLE
Automate contributions better

### ISSUE THREAD

**Issue by bdeanindy** [SparkPost/sparkpost-api-documentation#6]
Implement a Git pre-commit hook to:
- [ ] Execute `grunt compile`
- [ ] Continue pre-commit processing if compiler completes tests without errors, or notify contributor
- [ ] Amend the newly compiled apiary.apib file to the existing commit
- [ ] Continue commit process if compiler completes without errors, or notify contributor of issues

**Comment by colestrode** [comment]
This is out of date, I'm closing it.
